In [4]:
from classes import *
import pandas as pd

In [5]:
main_study = xmap_study('data/02_assay_data.xlsx', control_cols=slice(-4, None))
main_study.attach_patient_data(pd.read_excel('data/02_patient_data_cleaned.xlsx', index_col=0))

In [7]:
main_study.adj_mfi_data.head(3)

,SELE_HPRR2550021,IL6R_HPRR2760260,IQSEC1_HPRR2960328,SELE_HPRR2550018,CFTR_HPRR670001,IL6R_HPRR330033,VAV2_HPRR520084,GLI3_HPRR260114,CAPZA2_HPRR1920128,EEF2_HPRR1510035,...,CLTCL1_HPRR4290066,TOB2_HPRR4290698,DBNDD1_HPRR4290097,MSANTD4_HPRR4220490,CAPZA2*_HPRR4470064,PALM2AKAP2_HPRR4430321,VAV2_HPRR4370231,STMN4_HPRR4470056,CFTR_HPRR4320110,ENDOV_HPRR4120170
1,1.727578,204.727578,1.0,1.000000,7.727578,5.727578,6.727578,1.0,1.0,1.0,...,30.727578,6.727578,10.727578,26.727578,1.727578,10.727578,13.727578,3.727578,7.727578,9.727578
2,3.727578,2.727578,1.0,8.727578,1.000000,8.727578,6.727578,1.0,1.0,1.0,...,1.000000,1.727578,3.727578,3.727578,1.000000,2.727578,4.727578,1.000000,1.000000,3.727578
3,1.000000,1.000000,1.0,1.000000,1.000000,2.727578,2.727578,1.0,1.0,1.0,...,2.727578,2.727578,9.727578,5.727578,1.000000,2.727578,7.727578,1.000000,1.000000,5.727578

In [8]:
main_study.patient_data.head(3)

,Age,Sex,Diabetes,Hereditary,Hypertension,Migraine,Smoking,VA,Unilateral,SE,...,MD_3,VFI_3,ROP_Percent,Prog,GPA,Medicine_Count,SLT,Catop_3,Medicine_List,Active_Ingredients
Patient ID,,,,,,,,,,,,,,,,,,,,,
1,69,0,0,Mor,1,0,0,1.0,0,0.25,...,-11.7,72,-5.3,1,Possible progression,3,1,0,"['Azopt', 'Xalcom']","['brinzolamid', 'latanoprost', 'timolol']"
2,73,1,0,0,1,0,0,0.9,1,0.50,...,-7.2,90,-0.8,0,No progression,2,0,0,NaN,['None']
3,80,1,0,0,0,0,0,0.8,1,0.75,...,-6.2,88,-0.9,0,No progression,2,0,0,NaN,['None']